version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-rails-app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dreams_r_us_development # Replace with your actual database name
      POSTGRES_USER: dreams_r_us # Replace with your actual database user
      POSTGRES_PASSWORD: password # Replace with your actual database password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf   # Specify the custom configuration file
    volumes:
      - ./redis.conf:/etc/redis/redis.conf        # Mount the custom configuration

volumes:
  postgres_data:
